enum MessageType {
  GET_WALLETS = 'GET_WALLETS',
  WALLETS = 'WALLETS',
  GET_DEPLOY_CONTRACTS = 'GET_DEPLOY_CONTRACTS',
  DEPLOY_CONTRACTS = 'DEPLOY_CONTRACTS',
  GET_ENVIRONMENTS = 'GET_ENVIRONMENTS',
  ENVIRONMENTS = 'ENVIRONMENTS',
  EDIT_WALLETS = 'EDIT_WALLETS',
  EDIT_ENVIRONMENT = 'EDIT_ENVIRONMENT',
  DEPLOY_CONTRACT = 'DEPLOY_CONTRACT',
  DEPLOY_CONTRACT_RESPONSE = 'DEPLOY_CONTRACT_RESPONSE',
  UNKNOWN = 'UNKNOWN',
}

enum InputAction {
  ADD = 'Add',
  REMOVE = 'Remove',
}

export { MessageType, InputAction };
